### ISSUE TITLE
Issues setting up environment

### ISSUE THREAD

**Issue by mjahanshahi** [nficano/gendo#137]
Hi Nick!
This looks like an awesome library and I am so excited to use it to update our current slackbot. 

I've followed instructions as suggested and am running into environmental/dependency issues getting the basic bot script to work. This is the error I'm getting:
```
Traceback (most recent call last):
  File "<REDACTED>/bot.py", line 2, in <module>
    from tangerine import Tangerine
  File "<VENV_REDACTED>/lib/python3.7/site-packages/tangerine/__init__.py", line 10, in <module>
    from .bot import Tangerine
  File <VENV_REDACTED>/lib/python3.7/site-packages/tangerine/bot.py", line 17, in <module>
    from slackclient import SlackClient
ModuleNotFoundError: No module named 'slackclient'
```
And here is my Pipfile:
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
slack-tangerine = "*"
crontab = "*"
jinja2 = "*"
python-box = "*"
pyyaml = "*"
six = "*"
slackclient = "2.9.3"

[requires]
python_version = "3.7"
```
And it shows the Pipfile.lock reflects the slackclient. 
```
        },
        "slack-tangerine": {
            "hashes": [
                "sha256:92fa45aa2c2c75594212375a82a52e1ff8edc94b5dcb18b9d626efcc14367fce",
                "sha256:b513504e26d21d6d0421d7edf0eb8417f6b57e6fb078b6cec0d0ca80558eb8a8"
            ],
            "index": "pypi",
            "version": "==5.1.0"
        },
        "slackclient": {
            "hashes": [
                "sha256:07ec8fa76f6aa64852210ae235ff9e637ba78124e06c0b07a7eeea4abb955965",
                "sha256:2d68d668c02f4038299897e5c4723ab85dd40a3548354924b24f333a435856f8"
            ],
            "index": "pypi",
            "version": "==2.9.3"
        },
```

**Comment by mjahanshahi** [comment]
I think I figured it out. It turns out recent versions of the `slackclient` is installed in the `slack` folder.
The change I made was to `bot.py` in tangerine on line 17 replacing it with `from slack import WebClient` and updating line 47 to reflect the WebClient.

**Comment by mjahanshahi** [comment]
Actually its not completely solved. The version of Slackclient that is in the Pipfile has deprecated the `rtm_read` and `rtm_send_message` methods to be consistent with the RTM Slack API. If you have any fixes or suggestions, I'd love to hear them!
